cask_args appdir: "/Applications"
tap "homebrew/cask"
tap "homebrew/cask-versions"

# if these are on nix, move them.
# todo - maybe replace these with nixpkgs if they work

brew "mas"
brew "dog"
brew "git-delta" # on nix but seems outdated
brew "koekeishiya/formulae/yabai"
brew "glances"
brew "datasette"
brew "sqlite-utils"
brew "rinchsan/tap/gosimports"
brew "comby"

tap "noborus/tap"
brew "noborus/tap/trdsql"

cask "alfred"
cask "amethyst"
cask "caffeine"
cask "dash"
cask "db-browser-for-sqlite"
cask "docker"
cask "dropbox"
cask "firefox-developer-edition"
cask "gitkraken"
cask "google-chrome"
cask "google-cloud-sdk"
cask "graphiql"
cask "graphql-playground"
cask "iterm2"
cask "jetbrains-toolbox"
cask "karabiner-elements"
cask "kitty"
cask "macdown"
cask "macvim"
cask "notion"
cask "paste"
cask "pdf-expert"
cask "phoenix"
cask "postman"
cask "raycast"
cask "sequel-pro"
cask "slack"
cask "spotify"
cask "sublime-text"
cask "telegram"
cask "visual-studio-code"
cask "libreoffice"
cask "maccy"
