alias cb='cargo build'
alias cch='cargo check'
alias ccl='cargo clippy'
alias cf='cargo fmt -v'
alias ci='cargo install'
alias cr='cargo run'
alias ct='cargo test'
alias cw='cargo watch'
alias cwr='cargo watch -x run'
alias cwcl='cargo watch -x clippy'
alias cwch='cargo watch -x clippy'

# same but r can be more convenient s/c/r/
alias rb='cargo build'
alias rch='cargo check'
alias rcl='cargo clippy'
alias rf='cargo fmt -v'
alias ri='cargo install'
alias rr='cargo run'
alias rt='cargo test'
alias rw='cargo watch'
alias rwr='cargo watch -x run'
alias rwcl='cargo watch -x clippy'
alias rwch='cargo watch -x clippy'
